# Generated by Django 5.0.1 on 2024-01-14 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_article_options_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 10, 32, 56, 351215, tzinfo=datetime.timezone.utc), verbose_name='انتشار'),
        ),
    ]
